name: Test action

on:
  workflow_dispatch:
  push:

jobs:
  test_valid:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run action
        id: action_run
        uses: ./
        with:
          context: test_valid
          state: success
          description: Valid test commit status


  test_invalid_description:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run action
        id: action_run
        uses: ./
        with:
          continue-on-error: true
          context: test_invalid_description
          state: error
          description: 'A description that will exceed the maximum number of characters that can be used for a commit status description in the API. The current limit is 140 characters but might change in the future?'

      - name: Fail if action succeeded
        if: steps.action_run.outcome != 'failure'
        run: exit 1